In [3]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [5]:
df.isnull().sum()
df.dropna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

# Data Pre-processing

In [6]:
!pip install sweetviz

Requirement already satisfied: sweetviz in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (2.3.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from sweetviz) (2.3.3)
Requirement already satisfied: numpy>=1.16.0 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from sweetviz) (2.3.5)
Requirement already satisfied: matplotlib>=3.1.3 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from sweetviz) (3.10.6)
Requirement already satisfied: tqdm>=4.43.0 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from sweetviz) (4.67.1)
Requirement already satisfied: scipy>=1.3.2 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from sweetviz) (1.16.3)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib-resources>=1.2.0 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from sweetviz) (6.5.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from jinja2>=2.11.1->sweetviz) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Requirement already satisfied: colorama in c:\users\venkata dilip\anaconda3\anaconda3\lib\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.6)

In [7]:
import numpy as np
import warnings

#Avoid warning's
if not hasattr(np, 'VisibleDeprecationWarning'):
    np.VisibleDeprecationWarning = DeprecationWarning

import sweetviz as sv
import seaborn as sns
#load dataset
df=pd.read_csv("heart.csv")
# generate autamatic EDA Report
report = sv.analyze(df)
report.show_html("HEART_AUTOGEN_EDA.html")


from IPython.display import IFrame

# Embed Titanic Sweetviz report
IFrame("HEART_AUTOGEN_EDA.html", width=1200, height=600)

                                             |          | [  0%]   00:00 -> (? left)

Report HEART_AUTOGEN_EDA.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [8]:
df['target']=(df['target']>0).astype(int)
print(f"Healthy:{sum(df['target']==0)}")
print(f"Heart Disease:{sum(df['target']==1)}")

Healthy:499
Heart Disease:526

In [9]:
x=df.drop('target',axis=1)
y=df['target']

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

# Decision tree

In [12]:
from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier(max_depth=5,random_state=42)
dt_model
dt_model.fit(x_train,y_train)
dt_pred=dt_model.predict(x_test)
from sklearn.metrics import accuracy_score
dt_acc=accuracy_score(y_test,dt_pred)
dt_acc

0.8439024390243902

# RANDOM FOREST

In [13]:
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier(max_depth=5,random_state=42)
rf_model
rf_model.fit(x_train,y_train)
rf_pred=rf_model.predict(x_test)
from sklearn.metrics import accuracy_score
rf_acc=accuracy_score(y_test,rf_pred)
print(rf_acc)

0.8731707317073171

# KNN

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=5,
                               metric='euclidean',
                               weights='uniform')
knn_model
knn_model.fit(x_train,y_train)
knn_pred=knn_model.predict(x_test)
from sklearn.metrics import accuracy_score
knn_acc=accuracy_score(y_test,knn_pred)
print(knn_acc)
knn_model

0.7317073170731707

KNeighborsClassifier(metric='euclidean')

IMP TOPICS AND KEY NOTES

CASE 1: Always use KNeighborsClassifier() blank 1st check its optimize or not

Case2: If its not optimize use the following parameters

weights uniform' or 'distance'

n_neighbours

2 to 8

metric 'euclidean', '

manhattan'

# Logistic Regression

In [17]:
from sklearn.linear_model import LogisticRegression
lr_model=LogisticRegression(max_iter=1000)
lr_model
lr_model.fit(x_train,y_train)
lr_pred=lr_model.predict(x_test)
from sklearn.metrics import accuracy_score
lr_acc=accuracy_score(y_test,lr_pred)
print(lr_acc)

Accuracy: 0.7951219512195122

note : max_iter=1000, random_state=42 only use when accuracy is less

scaled data only use that time when accuracy is very low for Lgr

# Naive Bayes

In [88]:
from sklearn.naive_bayes import GaussianNB
nb_model=GaussianNB()
nb_model
nb_model.fit(x_train,y_train)
nb_pred=nb_model.predict(x_test)
from sklearn.metrics import accuracy_score
nb_acc=accuracy_score(y_test,nb_pred)
print(nb_acc)

0.8

note: nb scaling is not required
Note: Naive Bayes is probabilty based model since scaled is not required 
but in worest condition we used

# SVM.SVClassifier

In [90]:
from sklearn.svm import SVC
svc_model=SVC(kernel='rbf', C=1)
svc_model
svc_model.fit(x_train_scaled,y_train)
svc_pred=svc_model.predict(x_test_scaled)
from sklearn.metrics import accuracy_score
svc_acc=accuracy_score(y_test,svc_pred)
print(svc_acc)
svc_model

0.8878048780487805

SVC(C=1)

Notes IN svn its Distance based since scaling is manadatory.

1. always use SVC()--is empty and chek model is optimize or not
2.its not optimize then used the following paramters

Kernel = rbf or linear

C=6 or 1 (recommaded)

ranode_state=42 to 45

# Model camparision

In [91]:
model_accuracies={
    'DT':dt_acc,
    'RF':rf_acc,
    'SVM':svc_acc,
    'LgR':lr_acc,
    'NB':nb_acc,
    'KNN':knn_acc
}
model_accuracies

{'DT': 0.8439024390243902,
 'RF': 0.8731707317073171,
 'SVM': 0.8878048780487805,
 'LgR': 0.7951219512195122,
 'NB': 0.8,
 'KNN': 0.7317073170731707}

In [92]:
best_model_name=max(model_accuracies, key=model_accuracies.get)
best_accuracy=model_accuracies[best_model_name]
print(f"\n Best Model: {best_model_name} with accuracy of {best_accuracy:4f}")

 Best Model: SVM with accuracy of 0.887805

# Model Saving

In [94]:
import joblib
joblib.dump(svc_model, "heart_model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']